language: node_js
sudo: false
node_js:
  - 6.9.1
env:
  global:
    
install:
  - npm install karma-es6-shim
  - npm install
before_script: null
after_script:
  - process.exit()
after_success:
  - chmod +x ./config/deploy.sh
  - ./config/deploy.sh
cache:
  directories:
    - $HOME/.nvm
    - node_modules
